### ISSUE TITLE
Multiple Panes in One App

### ISSUE THREAD

**Issue by ChristopherJohnson25** [Devrax/v2-cupertino#1]
Opening one pane causes the other to open. Does each one need to be destroyed on close?

**Comment by Devrax** [comment]
Interesting, maybe is because both pane are using the same object reference, I'll check, anyway your explanation is somewhat vague for me.

**Comment by ChristopherJohnson25** [comment]
Sorry for being vague, here's both elements, I'm not doing anything special, just standard implementation.

1. 

```
v2-cupertino(
    :isPresent="open",
    :drawerOptions="drawerOptions"
)
    MoneyButton(
      :to="address"
      amount="0.0001"
      currency="BSV"
      label="Send some loot"
      @payment="handlePayment"
    )
```

2. 

```
        v2-cupertino(
            :isPresent="drawerOpen",
            @did-dismiss="drawerOpen = false",
            :drawerOptions="drawerOptions"
        )
            div(class="hexLaunchWidget__paneContent mt-2 mb-2")
                h1 You cannot undo this. Your hex will be lost forever.
```

**Comment by Devrax** [comment]
Much better, as I see it, you are using two different components, in that case, to open one you must destroy the other not hide it, because both the first and the second use the same reference class, in this case ' class="cupertino-pane" ', I could solve it by adding a custom prop id for those cases.

At the beginning I did not see that because I thought they would tend to use conditional rendering, in that way you would only have one pane that shows up the data dinamycally, but I will handle that case too, within 4 or 5 hours I will fix it, I'm working right now in other stuff. 💻

**Comment by ChristopherJohnson25** [comment]
Ok, thank you! I will also try some fixes on my end.

**Comment by Devrax** [comment]
I added a new prop id to solve it, give it a try now :)

**Comment by ChristopherJohnson25** [comment]
Works perfect, thank you!!
